# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание 1

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [13]:
a1 = torch.tensor(a)
a1

tensor([[0.3745, 0.9507, 0.7320],
        [0.5987, 0.1560, 0.1560],
        [0.0581, 0.8662, 0.6011],
        [0.7081, 0.0206, 0.9699],
        [0.8324, 0.2123, 0.1818]], dtype=torch.float64)

In [18]:
# ваш код здесь
torch.transpose(a1,0,1)

tensor([[0.3745, 0.5987, 0.0581, 0.7081, 0.8324],
        [0.9507, 0.1560, 0.8662, 0.0206, 0.2123],
        [0.7320, 0.1560, 0.6011, 0.9699, 0.1818]], dtype=torch.float64)

In [20]:
a1@torch.transpose(a1,0,1)

tensor([[1.5800, 0.4867, 1.2853, 0.9947, 0.6468],
        [0.4867, 0.4071, 0.2637, 0.5784, 0.5598],
        [1.2853, 0.2637, 1.1150, 0.6420, 0.3416],
        [0.9947, 0.5784, 0.6420, 1.4425, 0.7702],
        [0.6468, 0.5598, 0.3416, 0.7702, 0.7711]], dtype=torch.float64)

In [ ]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [ ]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание 2

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [21]:
# ваш код здесь
import numpy as np

# Создаем массив от 1 до 10000
numbers = np.arange(1, 10001)

# Возводим каждый элемент массива в квадрат и суммируем
sum_of_squares = np.sum(numbers**2)

print(sum_of_squares)


333383335000


Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [22]:
x = torch.rand(5, 3)
x

tensor([[0.7228, 0.7703, 0.6820],
        [0.0471, 0.2039, 0.3661],
        [0.8829, 0.0216, 0.2927],
        [0.0184, 0.7797, 0.9827],
        [0.6923, 0.0533, 0.5214]])

In [23]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [24]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.7228, 5.7703, 5.6820],
        [5.0471, 5.2039, 5.3661],
        [5.8829, 5.0216, 5.2927],
        [5.0184, 5.7797, 5.9827],
        [5.6923, 5.0533, 5.5214]])



In [25]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.5809, 0.4408, 0.8544, 1.2841, 0.8970],
        [0.4408, 0.1778, 0.1532, 0.5196, 0.2343],
        [0.8544, 0.1532, 0.8657, 0.3207, 0.7650],
        [1.2841, 0.5196, 0.3207, 1.5739, 0.5666],
        [0.8970, 0.2343, 0.7650, 0.5666, 0.7540]])

X*X^T  (2):
tensor([[1.5809, 0.4408, 0.8544, 1.2841, 0.8970],
        [0.4408, 0.1778, 0.1532, 0.5196, 0.2343],
        [0.8544, 0.1532, 0.8657, 0.3207, 0.7650],
        [1.2841, 0.5196, 0.3207, 1.5739, 0.5666],
        [0.8970, 0.2343, 0.7650, 0.5666, 0.7540]])



In [26]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.7250, 0.2057, 0.3991, 0.5936, 0.4223])



In [27]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [28]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-28-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [29]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22],
        [2.1715e-18, 4.2131e+21, 4.2190e-08],
        [1.0548e-08, 1.7183e-04, 7.9878e+20]])


In [30]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.5352, 0.2015, 0.2946],
        [0.5708, 0.8158, 0.7510],
        [0.7847, 0.4716, 0.9657],
        [0.8112, 0.5332, 0.0090],
        [0.1433, 0.3734, 0.3102]])


In [31]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [32]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [33]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [34]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 0.5856,  1.9433,  1.4651],
        [ 1.7016, -0.1675, -0.2077],
        [ 1.7703,  1.3997, -1.2828],
        [ 0.2291,  0.2671,  0.5831],
        [-1.7461,  0.2325,  0.1698]]) torch.Size([5, 3])


## Задание 3

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [36]:
torch.manual_seed(42)

x = torch.rand(5, 3)
y = torch.rand(5, 3)

x + y

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])

In [37]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание 4

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [41]:
# your code here

torch.matmul(x,y.transpose(1,0))

tensor([[1.4088, 0.9125, 0.9795, 0.4769, 0.6789],
        [1.1025, 0.6627, 1.0391, 0.4219, 0.4086],
        [1.3528, 0.8200, 1.1313, 0.5785, 0.4912],
        [1.2254, 0.7820, 0.8300, 0.4789, 0.5416],
        [1.3013, 0.7878, 1.1686, 0.5105, 0.4885]])

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
# b @ a