# Введение PyTorch

В данном ноутбуке мы познакомимся с фреймворком PyTorch

## Импорт библиотек

In [1]:
import numpy as np
import torch

In [2]:
from IPython.display import display

## PyTorch vs NumPy

Интерфейс `PyTorch` реализован подобно интерфесу `NumPy` для удобства использования. Главное различие между ними, что `NumPy` оперрирует `numpy.ndarray` массивами, а `PyTorch` &mdash; тензорами `pytorch.Tensor`. Напишем одни и те же операции на `NumPy` и `PyTorch`.

### NumPy

In [3]:
x = np.arange(16).reshape(4, 4)

In [4]:
print(f"Матрица X:\n{x}\n")
print(f"Размер: {x.shape}\n")
print(f"Добавление константы:\n{x + 5}\n")
print(f"X*X^T:\n{np.dot(x, x.T)}\n")
print(f"Среднее по колонкам:\n{x.mean(axis=-1)}\n")
print(f"Кумулятивная сумма по колонкам:\n{np.cumsum(x, axis=0)}\n")

Матрица X:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Размер: (4, 4)

Добавление константы:
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

X*X^T:
[[ 14  38  62  86]
 [ 38 126 214 302]
 [ 62 214 366 518]
 [ 86 302 518 734]]

Среднее по колонкам:
[ 1.5  5.5  9.5 13.5]

Кумулятивная сумма по колонкам:
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]]



### PyTorch

In [5]:
x = np.arange(16).reshape(4, 4)
x = torch.tensor(x, dtype=torch.float32)

display(x, x.dtype)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

torch.float32

ИЛИ

In [6]:
x = torch.arange(0, 16, dtype=torch.float32).view(4, 4)

display(x, x.dtype)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

torch.float32

In [7]:
print(f"Матрица X:\n{x}\n")
print(f"Размер: {x.shape}\n")
print(f"Добавление константы:\n{x + 5}")
print(f"X*X^T:\n{torch.matmul(x, x.transpose(1, 0))}\n")  # кратко: x.mm(x.t())
print(f"Среднее по колонкам:\n{torch.mean(x, dim=-1)}\n")
print(f"Кумулятивная сумма по колонкам:\n{torch.cumsum(x, dim=0)}")

Матрица X:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

Размер: torch.Size([4, 4])

Добавление константы:
tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])
X*X^T:
tensor([[ 14.,  38.,  62.,  86.],
        [ 38., 126., 214., 302.],
        [ 62., 214., 366., 518.],
        [ 86., 302., 518., 734.]])

Среднее по колонкам:
tensor([ 1.5000,  5.5000,  9.5000, 13.5000])

Кумулятивная сумма по колонкам:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.]])


Заметим, что некоторые названия методов отличаются и полной совместимости библиотек пока нет, и придется сново запоминать новые названия для некоторых функций.

Например, PyTorch имеет другое написание стандартных типов
 * `x.astype('int64') -> x.type(torch.LongTensor)`


Для более подробного ознакомления можно посмотреть на [таблицу](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users) перевода методов из NumPy в PyTorch, а также заглянуть в [документацию](http://pytorch.org/docs/master/).

### Конвертация из NumPy в PyTorch (и обратно)

Можно переводить numpy-массив в torch-тензор и наоборот.

Например, сделаем из numpy-массива torch-тензор

In [8]:
# зададим numpy массив
x_np = np.array([2, 5, 7, 1])

# 1-й способ
x_torch = torch.tensor(x_np)
print(type(x_torch), x_torch)

# 2-й способ
x_torch = torch.from_numpy(x_np)
print(type(x_torch), x_torch)

<class 'torch.Tensor'> tensor([2, 5, 7, 1])
<class 'torch.Tensor'> tensor([2, 5, 7, 1])


Аналогично и с переводом обратно:  
функция `x.numpy()` переведет torch-тензор `x` в numpy-массив, причем типы переведутся соответственно таблице

In [9]:
x_np = x_torch.numpy()
print(type(x_np), x_np)

<class 'numpy.ndarray'> [2 5 7 1]


## Создание и инициализация тензоров

### Создание тензоров

In [10]:
x = torch.tensor([ [0,1,2], [3,4,6] ])
x

tensor([[0, 1, 2],
        [3, 4, 6]])

Тензор можно создавать при помощи конструкторов. Доступны следующие типы:  


*  HalfTensor   - `float16`
*  FloatTensor  - `float32`
*  DoubleTensor - `float64`


*  ShortTensor  - `int16`
*  IntTensor    - `int32`
*  LongTensor   - `int64`
*  CharTensor   - `int8`


*  ByteTensor   - `uint8`
*  BoolTensor   - `bool`

In [11]:
x = torch.Tensor(2, 4)
x, x.dtype

(tensor([[-8.0680e+27,  4.5132e-41, -4.5427e+14,  3.3270e-41],
         [ 4.4842e-44,  0.0000e+00,  1.7937e-43,  0.0000e+00]]),
 torch.float32)

In [12]:
x = torch.FloatTensor(2, 4)
display(x)
display(x.dtype)

tensor([[ 1.4013e-45,  4.5130e-41, -4.6520e+27,  4.5132e-41],
        [-7.1295e+09,  4.5132e-41,  1.4013e-45,  4.5132e-41]])

torch.float32

In [13]:
x = torch.HalfTensor(2, 4)
display(x)
display(x.dtype)

tensor([[ 2.4219e-01, -1.2494e+02,  3.0350e+02,  0.0000e+00],
        [ 6.5625e+00, -1.2494e+02,  3.0350e+02,  0.0000e+00]],
       dtype=torch.float16)

torch.float16

In [14]:
x = torch.DoubleTensor(2, 4)
display(x)
display(x.dtype)

tensor([[5.0382e-310, 6.8343e-310, 4.9407e-324, 2.9644e-323],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],
       dtype=torch.float64)

torch.float64

In [15]:
x = torch.IntTensor(2, 4)
display(x)
display(x.dtype)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

torch.int32

In [16]:
x = torch.ShortTensor(2, 4)
display(x)
display(x.dtype)

tensor([[-29344,  -4656,  32207,      0],
        [ 10736, -10289,  23742,      0]], dtype=torch.int16)

torch.int16

In [17]:
x = torch.LongTensor(2, 4)
display(x)
display(x.dtype)

tensor([[138332001570192, 101974734213808, 101974734214512, 101974734217344],
        [              0, 101974734184192, 101974712191392, 138327991130192]])

torch.int64

Тип элементов можно также указывать в методе `empty()` или функциях инициализации

In [18]:
x_1 = torch.empty(2,3, dtype=torch.float64)
x_2 = torch.empty(2,3, dtype=torch.double)
y_1 = torch.zeros(2,3, dtype=torch.int64)
y_2 = torch.zeros(2,3, dtype=torch.long)

x_1, x_2, y_1, y_2

(tensor([[6.8345e-310, 6.8345e-310,  0.0000e+00],
         [7.1640e-322, 5.0382e-310, 5.0382e-310]], dtype=torch.float64),
 tensor([[6.8345e-310, 5.0382e-310, 5.0382e-310],
         [5.0382e-310,  0.0000e+00, 5.0382e-310]], dtype=torch.float64),
 tensor([[0, 0, 0],
         [0, 0, 0]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]))

Размер элемента

In [19]:
y_2.element_size()

8

### Инициализация значений

In [20]:
y = torch.zeros (2, 3)                   # матрица 2x3 из нулей  типа float32
x = torch.zeros_like(y)                  # такой же формы как y из нулей

x = torch.ones (2, 3)                    # матрица 2x3 из единиц
x = torch.ones_like(y)                   # такой же формы как y из единиц

x = torch.full((2, 3), 3.14159265)       # заполнить матрицу 2x3 числом pi

x = torch.eye   (3)                      # единичная матрица 3x3
x = torch.eye   (2,3)                    # "единичная" не квадратная [[1., 0., 0.],
                                         #                            [0., 1., 0.]]
x = torch.linspace(0,2,5)                # [0.0,0.5,1.0,1.5,2.0] [beg,end], num

x = torch.rand (2, 3)                    # 2x3 равномерно случ.матрица [0...1]
x = torch.randn(2, 3)                    # 2x3 нормально  случ.матрица (mean=0, var=1)

x = torch.empty(3).uniform_(0, 1)        # вектор с равномерным распределением [0..1]
x = torch.empty(3).normal_(mean=0,std=1) # вектор с нормальным распределением

In [21]:
x = torch.arange(4)                      # [0,1,2,3]             [0,end)
x = torch.arange(2, 14, 3)               # [2,5,8,11]            [beg,end), step

x = torch.randperm(10)                   # [8,6,9,3,5,0,1,4,7,2] - случ.перестановка
x = torch.randint (1, 10, (2,3))         # 2x3 случ.целых из интервала [1...10)

## Операции над тензорами

### Арифметические операции

In [22]:
x = torch.ones(2, 3).to(torch.int32)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [23]:
y = x * -1
y

tensor([[-1, -1, -1],
        [-1, -1, -1]], dtype=torch.int32)

In [24]:
# x.add(y)
x + y

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [25]:
# x.sub(y)
x - y

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [26]:
# x.mul(y)
x * y

tensor([[-1, -1, -1],
        [-1, -1, -1]], dtype=torch.int32)

In [27]:
# x.div(y)
x / y

tensor([[-1., -1., -1.],
        [-1., -1., -1.]])

In [28]:
a = x.detach().clone()
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [29]:
a.add_(y)
a

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [30]:
# `x` не изменился, потому что его "склонировали" в `a`
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [31]:
y.abs_()
y

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

### Логические операции

In [32]:
z = torch.FloatTensor(
    [
     [-1, 1, 1],
     [2, -1, -1]
    ]
)
z

tensor([[-1.,  1.,  1.],
        [ 2., -1., -1.]])

In [33]:
x > z

tensor([[ True, False, False],
        [False,  True,  True]])

In [34]:
x == z

tensor([[False,  True,  True],
        [False, False, False]])

In [35]:
x != z

tensor([[ True, False, False],
        [ True,  True,  True]])

In [36]:
mask = (x > z)
mask

tensor([[ True, False, False],
        [False,  True,  True]])

In [37]:
x[mask]

tensor([1, 1, 1], dtype=torch.int32)

### Скалярное произведение

In [38]:
x = torch.arange(1, 4).reshape(1, 3)
x

tensor([[1, 2, 3]])

In [39]:
y = -1 * x
y[0][1].abs_()
y

tensor([[-1,  2, -3]])

In [40]:
x @ y.T

tensor([[-6]])

In [41]:
torch.mm(x, y.T)

tensor([[-6]])

## Приведение типов

In [42]:
a = torch.IntTensor([1, 4, -2])
a

tensor([ 1,  4, -2], dtype=torch.int32)

In [43]:
a = a.type_as(torch.HalfTensor())
a

tensor([ 1.,  4., -2.], dtype=torch.float16)

In [44]:
a = a.to(torch.int32)
a

tensor([ 1,  4, -2], dtype=torch.int32)